

#pragma once

#define MILO_INTERNAL_PROJECT_NAME                      "milo"
#define MILO_INTERNAL_PROJECT_VERSION_MAJOR             0
#define MILO_INTERNAL_PROJECT_VERSION_MINOR             1
#define MILO_INTERNAL_PROJECT_VERSION_PATCH             0
#define MILO_INTERNAL_PROJECT_VERSION_INTEGRAL          uint64_t(0x0000000100000000)
#define MILO_INTERNAL_PROJECT_VERSION_SEMANTIC          "0.1.0"
