

#pragma once

#define MILO_INTERNAL_PROJECT_NAME                      "milo"
#define MILO_INTERNAL_PROJECT_VERSION_MAJOR             0
#define MILO_INTERNAL_PROJECT_VERSION_MINOR             2
#define MILO_INTERNAL_PROJECT_VERSION_PATCH             0
#define MILO_INTERNAL_PROJECT_VERSION_INTEGRAL          uint64_t(0x0000000200000000)
#define MILO_INTERNAL_PROJECT_VERSION_SEMANTIC          "0.2.0"
