

#pragma once

#define MILO_CONFIG_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define MILO_CONFIG_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define MILO_CONFIG_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define MILO_CONFIG_VERSION_TWEAK @PROJECT_VERSION_TWEAK@
