

#pragma once

#define MILO_INTERNAL_PROJECT_NAME                      "@PROJECT_NAME@"

#define MILO_INTERNAL_PROJECT_VERSION_MAJOR             @PROJECT_VERSION_MAJOR@
#define MILO_INTERNAL_PROJECT_VERSION_MINOR             @PROJECT_VERSION_MINOR@
#define MILO_INTERNAL_PROJECT_VERSION_PATCH             @PROJECT_VERSION_PATCH@

#define MILO_INTERNAL_PROJECT_VERSION_INTEGRAL          (uint64_t(MILO_INTERNAL_VERSION_MAJOR) << 48 | \
                                                         uint64_t(MILO_INTERNAL_VERSION_MINOR) << 32 | \
                                                         uint64_t(MILO_INTERNAL_VERSION_PATCH) << 16)

#define MILO_INTERNAL_PROJECT_VERSION_SEMANTIC          "@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@"
